
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  BrandAboutPage: typeof import("../../components/brand/AboutPage.vue")['default']
  BrandKunpengPage: typeof import("../../components/brand/KunpengPage.vue")['default']
  BrandNewsPage: typeof import("../../components/brand/NewsPage.vue")['default']
  BrandPhilosophyPage: typeof import("../../components/brand/PhilosophyPage.vue")['default']
  CommonBaseButton: typeof import("../../components/common/BaseButton.vue")['default']
  CommonMetricGrid: typeof import("../../components/common/MetricGrid.vue")['default']
  CommonPageHero: typeof import("../../components/common/PageHero.vue")['default']
  CorporatePage: typeof import("../../components/corporate/CorporatePage.vue")['default']
  CorporateIRPage: typeof import("../../components/corporate/IRPage.vue")['default']
  CorporateJoinUsPage: typeof import("../../components/corporate/JoinUsPage.vue")['default']
  CorporateRecruitPage: typeof import("../../components/corporate/RecruitPage.vue")['default']
  HomeBrandIntro: typeof import("../../components/home/HomeBrandIntro.vue")['default']
  HomeCommunity: typeof import("../../components/home/HomeCommunity.vue")['default']
  HomeGlobalMap: typeof import("../../components/home/HomeGlobalMap.vue")['default']
  HomeHero: typeof import("../../components/home/HomeHero.vue")['default']
  HomeModels: typeof import("../../components/home/HomeModels.vue")['default']
  HomeQuickActions: typeof import("../../components/home/HomeQuickActions.vue")['default']
  HomeServiceGrid: typeof import("../../components/home/HomeServiceGrid.vue")['default']
  HomeStatsMedia: typeof import("../../components/home/HomeStatsMedia.vue")['default']
  HomeTechnology: typeof import("../../components/home/HomeTechnology.vue")['default']
  LayoutSiteFooter: typeof import("../../components/layout/SiteFooter.vue")['default']
  LayoutSiteHeader: typeof import("../../components/layout/SiteHeader.vue")['default']
  LifestyleCommunityPage: typeof import("../../components/lifestyle/CommunityPage.vue")['default']
  LifestyleStorePage: typeof import("../../components/lifestyle/LifestyleStorePage.vue")['default']
  PageInfoPage: typeof import("../../components/page/InfoPage.vue")['default']
  PageLegalPage: typeof import("../../components/page/LegalPage.vue")['default']
  PageModelPage: typeof import("../../components/page/ModelPage.vue")['default']
  PageInfoDocumentRows: typeof import("../../components/page/info/InfoDocumentRows.vue")['default']
  PageInfoEditorialSections: typeof import("../../components/page/info/InfoEditorialSections.vue")['default']
  PageLegacyEnergyCenterPage: typeof import("../../components/page/legacy/EnergyCenterPage.vue")['default']
  PageLegacyBusinessPage: typeof import("../../components/page/legacy/LegacyBusinessPage.vue")['default']
  PageLegacyDisclosurePage: typeof import("../../components/page/legacy/LegacyDisclosurePage.vue")['default']
  PageLegacyServiceCenterPage: typeof import("../../components/page/legacy/ServiceCenterPage.vue")['default']
  PageLegacyStoreCenterPage: typeof import("../../components/page/legacy/StoreCenterPage.vue")['default']
  PageModelChapterNav: typeof import("../../components/page/model/ModelChapterNav.vue")['default']
  PageModelMediaSection: typeof import("../../components/page/model/ModelMediaSection.vue")['default']
  ServiceAppPage: typeof import("../../components/service/AppPage.vue")['default']
  ServiceFaqPage: typeof import("../../components/service/FaqPage.vue")['default']
  ServiceWarrantyPage: typeof import("../../components/service/WarrantyPage.vue")['default']
  TechArchitecturePage: typeof import("../../components/tech/ArchitecturePage.vue")['default']
  TechBatteryPage: typeof import("../../components/tech/BatteryPage.vue")['default']
  TechSafetyPage: typeof import("../../components/tech/SafetyPage.vue")['default']
  TechSmartCockpitPage: typeof import("../../components/tech/SmartCockpitPage.vue")['default']
  VehiclesCourageChapter: typeof import("../../components/vehicles/courage/CourageChapter.vue")['default']
  VehiclesCourageChapterNav: typeof import("../../components/vehicles/courage/CourageChapterNav.vue")['default']
  VehiclesCourageHero: typeof import("../../components/vehicles/courage/CourageHero.vue")['default']
  VehiclesCouragePage: typeof import("../../components/vehicles/courage/CouragePage.vue")['default']
  VehiclesDreamerChampionChapter: typeof import("../../components/vehicles/dreamer-champion/DreamerChampionChapter.vue")['default']
  VehiclesDreamerChampionChapterNav: typeof import("../../components/vehicles/dreamer-champion/DreamerChampionChapterNav.vue")['default']
  VehiclesDreamerChampionHero: typeof import("../../components/vehicles/dreamer-champion/DreamerChampionHero.vue")['default']
  VehiclesDreamerChampionPage: typeof import("../../components/vehicles/dreamer-champion/DreamerChampionPage.vue")['default']
  VehiclesDreamerChapter: typeof import("../../components/vehicles/dreamer/DreamerChapter.vue")['default']
  VehiclesDreamerChapterNav: typeof import("../../components/vehicles/dreamer/DreamerChapterNav.vue")['default']
  VehiclesDreamerHero: typeof import("../../components/vehicles/dreamer/DreamerHero.vue")['default']
  VehiclesDreamerPage: typeof import("../../components/vehicles/dreamer/DreamerPage.vue")['default']
  VehiclesDreamriverDreamRiverChapter: typeof import("../../components/vehicles/dreamriver/DreamRiverChapter.vue")['default']
  VehiclesDreamriverDreamRiverChapterNav: typeof import("../../components/vehicles/dreamriver/DreamRiverChapterNav.vue")['default']
  VehiclesDreamriverDreamRiverHero: typeof import("../../components/vehicles/dreamriver/DreamRiverHero.vue")['default']
  VehiclesDreamriverDreamRiverPage: typeof import("../../components/vehicles/dreamriver/DreamRiverPage.vue")['default']
  VehiclesFreeChapter: typeof import("../../components/vehicles/free/FreeChapter.vue")['default']
  VehiclesFreeChapterNav: typeof import("../../components/vehicles/free/FreeChapterNav.vue")['default']
  VehiclesFreeHero: typeof import("../../components/vehicles/free/FreeHero.vue")['default']
  VehiclesFreePage: typeof import("../../components/vehicles/free/FreePage.vue")['default']
  VehiclesFreePlusChapter: typeof import("../../components/vehicles/free_plus/FreePlusChapter.vue")['default']
  VehiclesFreePlusChapterNav: typeof import("../../components/vehicles/free_plus/FreePlusChapterNav.vue")['default']
  VehiclesFreePlusHero: typeof import("../../components/vehicles/free_plus/FreePlusHero.vue")['default']
  VehiclesFreePlusPage: typeof import("../../components/vehicles/free_plus/FreePlusPage.vue")['default']
  VehiclesInteractiveCinematicVideoHero: typeof import("../../components/vehicles/interactive/CinematicVideoHero.vue")['default']
  VehiclesInteractiveFeatureCarousel: typeof import("../../components/vehicles/interactive/FeatureCarousel.vue")['default']
  VehiclesInteractiveVehicleColorPicker: typeof import("../../components/vehicles/interactive/VehicleColorPicker.vue")['default']
  VehiclesNewCourageChapter: typeof import("../../components/vehicles/newCourage/NewCourageChapter.vue")['default']
  VehiclesNewCourageChapterNav: typeof import("../../components/vehicles/newCourage/NewCourageChapterNav.vue")['default']
  VehiclesNewCourageHero: typeof import("../../components/vehicles/newCourage/NewCourageHero.vue")['default']
  VehiclesNewCouragePage: typeof import("../../components/vehicles/newCourage/NewCouragePage.vue")['default']
  VehiclesNewDreamerChapter: typeof import("../../components/vehicles/newDreamer/NewDreamerChapter.vue")['default']
  VehiclesNewDreamerChapterNav: typeof import("../../components/vehicles/newDreamer/NewDreamerChapterNav.vue")['default']
  VehiclesNewDreamerHero: typeof import("../../components/vehicles/newDreamer/NewDreamerHero.vue")['default']
  VehiclesNewDreamerPage: typeof import("../../components/vehicles/newDreamer/NewDreamerPage.vue")['default']
  VehiclesNewDreamer26Chapter: typeof import("../../components/vehicles/newDreamer26/NewDreamer26Chapter.vue")['default']
  VehiclesNewDreamer26ChapterNav: typeof import("../../components/vehicles/newDreamer26/NewDreamer26ChapterNav.vue")['default']
  VehiclesNewDreamer26Hero: typeof import("../../components/vehicles/newDreamer26/NewDreamer26Hero.vue")['default']
  VehiclesNewDreamer26Page: typeof import("../../components/vehicles/newDreamer26/NewDreamer26Page.vue")['default']
  VehiclesPassionLChapter: typeof import("../../components/vehicles/passion-L/PassionLChapter.vue")['default']
  VehiclesPassionLChapterNav: typeof import("../../components/vehicles/passion-L/PassionLChapterNav.vue")['default']
  VehiclesPassionLHero: typeof import("../../components/vehicles/passion-L/PassionLHero.vue")['default']
  VehiclesPassionLPage: typeof import("../../components/vehicles/passion-L/PassionLPage.vue")['default']
  VehiclesPassionChapter: typeof import("../../components/vehicles/passion/PassionChapter.vue")['default']
  VehiclesPassionChapterNav: typeof import("../../components/vehicles/passion/PassionChapterNav.vue")['default']
  VehiclesPassionHero: typeof import("../../components/vehicles/passion/PassionHero.vue")['default']
  VehiclesPassionPage: typeof import("../../components/vehicles/passion/PassionPage.vue")['default']
  VehiclesTitanChapter: typeof import("../../components/vehicles/titan/TitanChapter.vue")['default']
  VehiclesTitanChapterNav: typeof import("../../components/vehicles/titan/TitanChapterNav.vue")['default']
  VehiclesTitanHero: typeof import("../../components/vehicles/titan/TitanHero.vue")['default']
  VehiclesTitanPage: typeof import("../../components/vehicles/titan/TitanPage.vue")['default']
  VehiclesTitanX8Chapter: typeof import("../../components/vehicles/titan_X8/TitanX8Chapter.vue")['default']
  VehiclesTitanX8ChapterNav: typeof import("../../components/vehicles/titan_X8/TitanX8ChapterNav.vue")['default']
  VehiclesTitanX8Hero: typeof import("../../components/vehicles/titan_X8/TitanX8Hero.vue")['default']
  VehiclesTitanX8Page: typeof import("../../components/vehicles/titan_X8/TitanX8Page.vue")['default']
  VehiclesTitanBlackeditionTitanBlackEditionChapter: typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionChapter.vue")['default']
  VehiclesTitanBlackeditionTitanBlackEditionChapterNav: typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionChapterNav.vue")['default']
  VehiclesTitanBlackeditionTitanBlackEditionHero: typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionHero.vue")['default']
  VehiclesTitanBlackeditionTitanBlackEditionPage: typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionPage.vue")['default']
  NuxtWelcome: typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
  NuxtLayout: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
  NuxtErrorBoundary: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
  ClientOnly: typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
  DevOnly: typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
  ServerPlaceholder: typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
  NuxtLink: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
  NuxtLoadingIndicator: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  NuxtTime: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
  NuxtRouteAnnouncer: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
  NuxtImg: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
  NuxtPicture: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
  NuxtLinkLocale: typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']
  SwitchLocalePathLink: typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']
  NuxtPage: typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
  NoScript: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
  Link: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
  Base: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
  Title: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
  Meta: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
  Style: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
  Head: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
  Html: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
  Body: typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
  NuxtIsland: typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
  LazyBrandAboutPage: LazyComponent<typeof import("../../components/brand/AboutPage.vue")['default']>
  LazyBrandKunpengPage: LazyComponent<typeof import("../../components/brand/KunpengPage.vue")['default']>
  LazyBrandNewsPage: LazyComponent<typeof import("../../components/brand/NewsPage.vue")['default']>
  LazyBrandPhilosophyPage: LazyComponent<typeof import("../../components/brand/PhilosophyPage.vue")['default']>
  LazyCommonBaseButton: LazyComponent<typeof import("../../components/common/BaseButton.vue")['default']>
  LazyCommonMetricGrid: LazyComponent<typeof import("../../components/common/MetricGrid.vue")['default']>
  LazyCommonPageHero: LazyComponent<typeof import("../../components/common/PageHero.vue")['default']>
  LazyCorporatePage: LazyComponent<typeof import("../../components/corporate/CorporatePage.vue")['default']>
  LazyCorporateIRPage: LazyComponent<typeof import("../../components/corporate/IRPage.vue")['default']>
  LazyCorporateJoinUsPage: LazyComponent<typeof import("../../components/corporate/JoinUsPage.vue")['default']>
  LazyCorporateRecruitPage: LazyComponent<typeof import("../../components/corporate/RecruitPage.vue")['default']>
  LazyHomeBrandIntro: LazyComponent<typeof import("../../components/home/HomeBrandIntro.vue")['default']>
  LazyHomeCommunity: LazyComponent<typeof import("../../components/home/HomeCommunity.vue")['default']>
  LazyHomeGlobalMap: LazyComponent<typeof import("../../components/home/HomeGlobalMap.vue")['default']>
  LazyHomeHero: LazyComponent<typeof import("../../components/home/HomeHero.vue")['default']>
  LazyHomeModels: LazyComponent<typeof import("../../components/home/HomeModels.vue")['default']>
  LazyHomeQuickActions: LazyComponent<typeof import("../../components/home/HomeQuickActions.vue")['default']>
  LazyHomeServiceGrid: LazyComponent<typeof import("../../components/home/HomeServiceGrid.vue")['default']>
  LazyHomeStatsMedia: LazyComponent<typeof import("../../components/home/HomeStatsMedia.vue")['default']>
  LazyHomeTechnology: LazyComponent<typeof import("../../components/home/HomeTechnology.vue")['default']>
  LazyLayoutSiteFooter: LazyComponent<typeof import("../../components/layout/SiteFooter.vue")['default']>
  LazyLayoutSiteHeader: LazyComponent<typeof import("../../components/layout/SiteHeader.vue")['default']>
  LazyLifestyleCommunityPage: LazyComponent<typeof import("../../components/lifestyle/CommunityPage.vue")['default']>
  LazyLifestyleStorePage: LazyComponent<typeof import("../../components/lifestyle/LifestyleStorePage.vue")['default']>
  LazyPageInfoPage: LazyComponent<typeof import("../../components/page/InfoPage.vue")['default']>
  LazyPageLegalPage: LazyComponent<typeof import("../../components/page/LegalPage.vue")['default']>
  LazyPageModelPage: LazyComponent<typeof import("../../components/page/ModelPage.vue")['default']>
  LazyPageInfoDocumentRows: LazyComponent<typeof import("../../components/page/info/InfoDocumentRows.vue")['default']>
  LazyPageInfoEditorialSections: LazyComponent<typeof import("../../components/page/info/InfoEditorialSections.vue")['default']>
  LazyPageLegacyEnergyCenterPage: LazyComponent<typeof import("../../components/page/legacy/EnergyCenterPage.vue")['default']>
  LazyPageLegacyBusinessPage: LazyComponent<typeof import("../../components/page/legacy/LegacyBusinessPage.vue")['default']>
  LazyPageLegacyDisclosurePage: LazyComponent<typeof import("../../components/page/legacy/LegacyDisclosurePage.vue")['default']>
  LazyPageLegacyServiceCenterPage: LazyComponent<typeof import("../../components/page/legacy/ServiceCenterPage.vue")['default']>
  LazyPageLegacyStoreCenterPage: LazyComponent<typeof import("../../components/page/legacy/StoreCenterPage.vue")['default']>
  LazyPageModelChapterNav: LazyComponent<typeof import("../../components/page/model/ModelChapterNav.vue")['default']>
  LazyPageModelMediaSection: LazyComponent<typeof import("../../components/page/model/ModelMediaSection.vue")['default']>
  LazyServiceAppPage: LazyComponent<typeof import("../../components/service/AppPage.vue")['default']>
  LazyServiceFaqPage: LazyComponent<typeof import("../../components/service/FaqPage.vue")['default']>
  LazyServiceWarrantyPage: LazyComponent<typeof import("../../components/service/WarrantyPage.vue")['default']>
  LazyTechArchitecturePage: LazyComponent<typeof import("../../components/tech/ArchitecturePage.vue")['default']>
  LazyTechBatteryPage: LazyComponent<typeof import("../../components/tech/BatteryPage.vue")['default']>
  LazyTechSafetyPage: LazyComponent<typeof import("../../components/tech/SafetyPage.vue")['default']>
  LazyTechSmartCockpitPage: LazyComponent<typeof import("../../components/tech/SmartCockpitPage.vue")['default']>
  LazyVehiclesCourageChapter: LazyComponent<typeof import("../../components/vehicles/courage/CourageChapter.vue")['default']>
  LazyVehiclesCourageChapterNav: LazyComponent<typeof import("../../components/vehicles/courage/CourageChapterNav.vue")['default']>
  LazyVehiclesCourageHero: LazyComponent<typeof import("../../components/vehicles/courage/CourageHero.vue")['default']>
  LazyVehiclesCouragePage: LazyComponent<typeof import("../../components/vehicles/courage/CouragePage.vue")['default']>
  LazyVehiclesDreamerChampionChapter: LazyComponent<typeof import("../../components/vehicles/dreamer-champion/DreamerChampionChapter.vue")['default']>
  LazyVehiclesDreamerChampionChapterNav: LazyComponent<typeof import("../../components/vehicles/dreamer-champion/DreamerChampionChapterNav.vue")['default']>
  LazyVehiclesDreamerChampionHero: LazyComponent<typeof import("../../components/vehicles/dreamer-champion/DreamerChampionHero.vue")['default']>
  LazyVehiclesDreamerChampionPage: LazyComponent<typeof import("../../components/vehicles/dreamer-champion/DreamerChampionPage.vue")['default']>
  LazyVehiclesDreamerChapter: LazyComponent<typeof import("../../components/vehicles/dreamer/DreamerChapter.vue")['default']>
  LazyVehiclesDreamerChapterNav: LazyComponent<typeof import("../../components/vehicles/dreamer/DreamerChapterNav.vue")['default']>
  LazyVehiclesDreamerHero: LazyComponent<typeof import("../../components/vehicles/dreamer/DreamerHero.vue")['default']>
  LazyVehiclesDreamerPage: LazyComponent<typeof import("../../components/vehicles/dreamer/DreamerPage.vue")['default']>
  LazyVehiclesDreamriverDreamRiverChapter: LazyComponent<typeof import("../../components/vehicles/dreamriver/DreamRiverChapter.vue")['default']>
  LazyVehiclesDreamriverDreamRiverChapterNav: LazyComponent<typeof import("../../components/vehicles/dreamriver/DreamRiverChapterNav.vue")['default']>
  LazyVehiclesDreamriverDreamRiverHero: LazyComponent<typeof import("../../components/vehicles/dreamriver/DreamRiverHero.vue")['default']>
  LazyVehiclesDreamriverDreamRiverPage: LazyComponent<typeof import("../../components/vehicles/dreamriver/DreamRiverPage.vue")['default']>
  LazyVehiclesFreeChapter: LazyComponent<typeof import("../../components/vehicles/free/FreeChapter.vue")['default']>
  LazyVehiclesFreeChapterNav: LazyComponent<typeof import("../../components/vehicles/free/FreeChapterNav.vue")['default']>
  LazyVehiclesFreeHero: LazyComponent<typeof import("../../components/vehicles/free/FreeHero.vue")['default']>
  LazyVehiclesFreePage: LazyComponent<typeof import("../../components/vehicles/free/FreePage.vue")['default']>
  LazyVehiclesFreePlusChapter: LazyComponent<typeof import("../../components/vehicles/free_plus/FreePlusChapter.vue")['default']>
  LazyVehiclesFreePlusChapterNav: LazyComponent<typeof import("../../components/vehicles/free_plus/FreePlusChapterNav.vue")['default']>
  LazyVehiclesFreePlusHero: LazyComponent<typeof import("../../components/vehicles/free_plus/FreePlusHero.vue")['default']>
  LazyVehiclesFreePlusPage: LazyComponent<typeof import("../../components/vehicles/free_plus/FreePlusPage.vue")['default']>
  LazyVehiclesInteractiveCinematicVideoHero: LazyComponent<typeof import("../../components/vehicles/interactive/CinematicVideoHero.vue")['default']>
  LazyVehiclesInteractiveFeatureCarousel: LazyComponent<typeof import("../../components/vehicles/interactive/FeatureCarousel.vue")['default']>
  LazyVehiclesInteractiveVehicleColorPicker: LazyComponent<typeof import("../../components/vehicles/interactive/VehicleColorPicker.vue")['default']>
  LazyVehiclesNewCourageChapter: LazyComponent<typeof import("../../components/vehicles/newCourage/NewCourageChapter.vue")['default']>
  LazyVehiclesNewCourageChapterNav: LazyComponent<typeof import("../../components/vehicles/newCourage/NewCourageChapterNav.vue")['default']>
  LazyVehiclesNewCourageHero: LazyComponent<typeof import("../../components/vehicles/newCourage/NewCourageHero.vue")['default']>
  LazyVehiclesNewCouragePage: LazyComponent<typeof import("../../components/vehicles/newCourage/NewCouragePage.vue")['default']>
  LazyVehiclesNewDreamerChapter: LazyComponent<typeof import("../../components/vehicles/newDreamer/NewDreamerChapter.vue")['default']>
  LazyVehiclesNewDreamerChapterNav: LazyComponent<typeof import("../../components/vehicles/newDreamer/NewDreamerChapterNav.vue")['default']>
  LazyVehiclesNewDreamerHero: LazyComponent<typeof import("../../components/vehicles/newDreamer/NewDreamerHero.vue")['default']>
  LazyVehiclesNewDreamerPage: LazyComponent<typeof import("../../components/vehicles/newDreamer/NewDreamerPage.vue")['default']>
  LazyVehiclesNewDreamer26Chapter: LazyComponent<typeof import("../../components/vehicles/newDreamer26/NewDreamer26Chapter.vue")['default']>
  LazyVehiclesNewDreamer26ChapterNav: LazyComponent<typeof import("../../components/vehicles/newDreamer26/NewDreamer26ChapterNav.vue")['default']>
  LazyVehiclesNewDreamer26Hero: LazyComponent<typeof import("../../components/vehicles/newDreamer26/NewDreamer26Hero.vue")['default']>
  LazyVehiclesNewDreamer26Page: LazyComponent<typeof import("../../components/vehicles/newDreamer26/NewDreamer26Page.vue")['default']>
  LazyVehiclesPassionLChapter: LazyComponent<typeof import("../../components/vehicles/passion-L/PassionLChapter.vue")['default']>
  LazyVehiclesPassionLChapterNav: LazyComponent<typeof import("../../components/vehicles/passion-L/PassionLChapterNav.vue")['default']>
  LazyVehiclesPassionLHero: LazyComponent<typeof import("../../components/vehicles/passion-L/PassionLHero.vue")['default']>
  LazyVehiclesPassionLPage: LazyComponent<typeof import("../../components/vehicles/passion-L/PassionLPage.vue")['default']>
  LazyVehiclesPassionChapter: LazyComponent<typeof import("../../components/vehicles/passion/PassionChapter.vue")['default']>
  LazyVehiclesPassionChapterNav: LazyComponent<typeof import("../../components/vehicles/passion/PassionChapterNav.vue")['default']>
  LazyVehiclesPassionHero: LazyComponent<typeof import("../../components/vehicles/passion/PassionHero.vue")['default']>
  LazyVehiclesPassionPage: LazyComponent<typeof import("../../components/vehicles/passion/PassionPage.vue")['default']>
  LazyVehiclesTitanChapter: LazyComponent<typeof import("../../components/vehicles/titan/TitanChapter.vue")['default']>
  LazyVehiclesTitanChapterNav: LazyComponent<typeof import("../../components/vehicles/titan/TitanChapterNav.vue")['default']>
  LazyVehiclesTitanHero: LazyComponent<typeof import("../../components/vehicles/titan/TitanHero.vue")['default']>
  LazyVehiclesTitanPage: LazyComponent<typeof import("../../components/vehicles/titan/TitanPage.vue")['default']>
  LazyVehiclesTitanX8Chapter: LazyComponent<typeof import("../../components/vehicles/titan_X8/TitanX8Chapter.vue")['default']>
  LazyVehiclesTitanX8ChapterNav: LazyComponent<typeof import("../../components/vehicles/titan_X8/TitanX8ChapterNav.vue")['default']>
  LazyVehiclesTitanX8Hero: LazyComponent<typeof import("../../components/vehicles/titan_X8/TitanX8Hero.vue")['default']>
  LazyVehiclesTitanX8Page: LazyComponent<typeof import("../../components/vehicles/titan_X8/TitanX8Page.vue")['default']>
  LazyVehiclesTitanBlackeditionTitanBlackEditionChapter: LazyComponent<typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionChapter.vue")['default']>
  LazyVehiclesTitanBlackeditionTitanBlackEditionChapterNav: LazyComponent<typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionChapterNav.vue")['default']>
  LazyVehiclesTitanBlackeditionTitanBlackEditionHero: LazyComponent<typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionHero.vue")['default']>
  LazyVehiclesTitanBlackeditionTitanBlackEditionPage: LazyComponent<typeof import("../../components/vehicles/titan_blackedition/TitanBlackEditionPage.vue")['default']>
  LazyNuxtWelcome: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
  LazyNuxtLayout: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
  LazyNuxtErrorBoundary: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
  LazyClientOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
  LazyDevOnly: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
  LazyServerPlaceholder: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
  LazyNuxtLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
  LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
  LazyNuxtTime: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
  LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
  LazyNuxtImg: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
  LazyNuxtPicture: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
  LazyNuxtLinkLocale: LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/NuxtLinkLocale")['default']>
  LazySwitchLocalePathLink: LazyComponent<typeof import("../../node_modules/@nuxtjs/i18n/dist/runtime/components/SwitchLocalePathLink")['default']>
  LazyNuxtPage: LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
  LazyNoScript: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
  LazyLink: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
  LazyBase: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
  LazyTitle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
  LazyMeta: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
  LazyStyle: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
  LazyHead: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
  LazyHtml: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
  LazyBody: LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
  LazyNuxtIsland: LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
